CREATE TABLE "GCG_4012_UMP_VND_INV"(
 "BIRUNID" BIGINT,
 "VENDOR" CHAR(7),
 "NAME_VENDOR" CHAR(30),
 "INVOICE" CHAR(15),
 "PURCHASE_ORDER" CHAR(7),
 "DATE_INVOICE" CHAR(10),
 "AMT_INVOICE" NUMERIC(10,2));